# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnSTlvo7xs0KVISWEcM6rHqn9bMfUJb8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("Concrete_Data.xlsx")
df.columns = df.columns.str.strip()

target = "Concrete compressive strength(MPa, megapascals)"
corr = df.corr(numeric_only=True)
print(corr[target].sort_values(ascending=False))

# ===== Summary statistics =====
summary = df.describe()
print(summary)

# ===== Correlation matrix =====
corr = df.corr()
print(corr["Concrete compressive strength(MPa, megapascals)"])

# ===== Histograms =====
plt.figure(figsize=(12,8))
df.hist(bins=20, figsize=(12,8))
plt.tight_layout()
plt.show()

# ===== Correlation heatmap =====
plt.figure(figsize=(8,6))
sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Feature Correlation Matrix")
plt.show()

# ===== Correlation matrix =====
corr = df.corr()
print(corr["Concrete compressive strength(MPa, megapascals)"])

# ===== Histograms =====
plt.figure(figsize=(12,8))
df.hist(bins=20, figsize=(12,8))
plt.tight_layout()
plt.show()

# ===== Correlation heatmap =====
plt.figure(figsize=(8,6))
sns.heatmap(corr, cmap="coolwarm", center=0)
plt.title("Feature Correlation Matrix")
plt.show()